name: Deploy Jupyter Book

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the book
        run: |
          pip install jupyter-book
          jupyter-book build .
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          path: "_build/html"

