name: deploy-book

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4  # Latest version
    
    - name: Set up Python
      uses: actions/setup-python@v5  # Latest version
      with:
        python-version: '3.9'  # More compatible version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book
        pip install -r requirements.txt
    
    - name: Build Book
      run: |
        jupyter-book build .
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

